export const ADD_BUN = 'ADD_BUN';
export const ADD_FILLING = 'ADD_FILLING';
export const DELETE_FILLING = 'DELETE_FILLING';
export const SWAP_FILLING = 'SWAP_FILLING';
export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR';
